import Navbar from "@/components/Navbar";
import FooterSection from "@/components/sections/FooterSection";

type PointTextProps = {
  title: string;
  text: string | React.ReactNode;
};

function PointText({ title, text }: PointTextProps) {
  return (
    <div className="flex flex-col gap-y-2">
      <h2 className="text-lg font-medium">{title}</h2>
      <div className="text-gray-700 leading-relaxed">{text}</div>
    </div>
  );
}

const TermsAndConditions = () => (
  <div className="flex flex-col gap-y-6">
    <div className="mb-4">
      <p className="text-gray-700 leading-relaxed">
        Welcome to Neuralix ("Neuralix," "we," "us," or "our"). These Terms of
        Service ("Terms") govern your access to and use of the Neuralix website,
        platform, products, services, and any related applications or content
        (collectively, the "Services"). By accessing or using our Services, you
        agree to be bound by these Terms.
      </p>
      <p className="text-gray-700 leading-relaxed mt-2">
        If you do not agree with these Terms, please do not use the Services.
      </p>
    </div>

    <PointText
      title="1. About Neuralix"
      text="Neuralix develops advanced AI-driven solutions, analytics, and software platforms, including applications related to energy, industrial systems, sustainability, and enterprise intelligence. Our Services may include data processing, predictive analytics, machine learning models, APIs, dashboards, and related professional or advisory services."
    />

    <PointText
      title="2. Eligibility"
      text="You must be at least 18 years old and capable of forming a binding contract to use the Services. By using the Services, you represent and warrant that you meet these requirements."
    />

    <div className="flex flex-col gap-y-2">
      <h2 className="text-lg font-medium">3. Use of the Services</h2>
      <div className="flex flex-col gap-y-3 text-gray-700 leading-relaxed">
        <div>
          <h3 className="font-medium mb-1">3.1 Permitted Use</h3>
          <p>
            You may use the Services solely for lawful business or personal
            purposes and in accordance with these Terms.
          </p>
        </div>
        <div>
          <h3 className="font-medium mb-1">3.2 Prohibited Use</h3>
          <p className="mb-2">You agree not to:</p>
          <ul className="list-disc list-inside space-y-1 ml-4">
            <li>Violate any applicable laws, regulations, or industry standards</li>
            <li>
              Reverse engineer, decompile, or attempt to extract source code or
              models
            </li>
            <li>
              Use the Services to develop competing products or services
            </li>
            <li>
              Interfere with or disrupt the security or performance of the
              Services
            </li>
            <li>Upload malicious code, malware, or harmful data</li>
            <li>Misrepresent your identity or affiliation</li>
          </ul>
        </div>
      </div>
    </div>

    <PointText
      title="4. Accounts and Access"
      text="Some features may require account registration. You are responsible for maintaining the confidentiality of your credentials and for all activity under your account. You agree to notify us promptly of any unauthorized access or use."
    />

    <PointText
      title="5. Intellectual Property"
      text={
        <>
          All content, software, models, algorithms, designs, trademarks, and
          documentation associated with the Services are owned by or licensed to
          Neuralix and are protected by intellectual property laws.
          <br />
          <br />
          Nothing in these Terms grants you ownership rights in the Services.
          Subject to compliance with these Terms, Neuralix grants you a limited,
          non-exclusive, non-transferable, revocable license to use the
          Services.
        </>
      }
    />

    <div className="flex flex-col gap-y-2">
      <h2 className="text-lg font-medium">6. Data and AI Outputs</h2>
      <div className="flex flex-col gap-y-3 text-gray-700 leading-relaxed">
        <div>
          <h3 className="font-medium mb-1">6.1 Input Data</h3>
          <p>
            You retain ownership of data you submit to the Services ("Input
            Data"). You grant Neuralix a limited license to process Input Data
            solely to provide and improve the Services.
          </p>
        </div>
        <div>
          <h3 className="font-medium mb-1">6.2 Outputs</h3>
          <p className="mb-2">
            Outputs generated by the Services may be probabilistic and based on
            patterns in data. Neuralix does not guarantee accuracy, completeness,
            or suitability of Outputs for any specific purpose.
          </p>
          <p>
            You are responsible for independently validating Outputs before
            relying on them for business, operational, regulatory, or
            safety-critical decisions.
          </p>
        </div>
      </div>
    </div>

    <PointText
      title="7. Confidentiality"
      text="Any non-public information disclosed by either party and marked or reasonably understood as confidential shall be protected using reasonable care and used solely for purposes related to the Services."
    />

    <PointText
      title="8. Third-Party Services"
      text="The Services may integrate with or link to third-party platforms or services. Neuralix is not responsible for third-party content, policies, or practices."
    />

    <PointText
      title="9. Fees and Payment"
      text="Certain Services may be subject to fees under separate agreements, proposals, or subscription plans. All fees are non-refundable unless otherwise stated in writing."
    />

    <PointText
      title="10. Disclaimers"
      text={
        <>
          THE SERVICES ARE PROVIDED "AS IS" AND "AS AVAILABLE." TO THE MAXIMUM
          EXTENT PERMITTED BY LAW, NEURALIX DISCLAIMS ALL WARRANTIES, EXPRESS OR
          IMPLIED, INCLUDING WARRANTIES OF MERCHANTABILITY, FITNESS FOR A
          PARTICULAR PURPOSE, AND NON-INFRINGEMENT.
        </>
      }
    />

    <PointText
      title="11. Limitation of Liability"
      text={
        <>
          TO THE MAXIMUM EXTENT PERMITTED BY LAW, NEURALIX SHALL NOT BE LIABLE
          FOR ANY INDIRECT, INCIDENTAL, CONSEQUENTIAL, SPECIAL, OR PUNITIVE
          DAMAGES, INCLUDING LOSS OF PROFITS, DATA, OR BUSINESS INTERRUPTION.
          <br />
          <br />
          NEURALIX'S TOTAL LIABILITY ARISING OUT OF OR RELATED TO THE SERVICES
          SHALL NOT EXCEED THE AMOUNT PAID BY YOU TO NEURALIX IN THE TWELVE (12)
          MONTHS PRECEDING THE CLAIM.
        </>
      }
    />

    <PointText
      title="12. Indemnification"
      text="You agree to indemnify and hold harmless Neuralix and its officers, directors, employees, and partners from any claims, damages, or liabilities arising from your use of the Services or violation of these Terms."
    />

    <PointText
      title="13. Termination"
      text="We may suspend or terminate access to the Services at any time for violation of these Terms or if required by law. Upon termination, all licenses granted herein will immediately cease."
    />

    <PointText
      title="14. Governing Law"
      text="These Terms are governed by the laws of the State of Texas, United States, without regard to conflict of law principles."
    />

    <PointText
      title="15. Changes to These Terms"
      text="We may update these Terms from time to time. Continued use of the Services after updates constitutes acceptance of the revised Terms."
    />

    <PointText
      title="16. Contact Information"
      text={
        <>
          For questions regarding these Terms, contact us at:{" "}
          <a
            href="mailto:info@neuralix.ai"
            className="text-teal-600 hover:text-teal-700 underline"
          >
            info@neuralix.ai
          </a>
        </>
      }
    />
  </div>
);

export default function TncPage() {
  return (
    <div className="min-h-screen flex flex-col">
      <Navbar />
      <div className="container mx-auto px-6 md:px-16 py-12 md:py-20 flex-1">
        <div className="max-w-4xl mx-auto">
          <div className="mb-8">
            <h1 className="text-3xl md:text-4xl font-semibold mb-2">
              Neuralix - Terms of Service
            </h1>
            <p className="text-gray-600">Last Updated: January 2026</p>
          </div>
          <TermsAndConditions />
        </div>
      </div>
      <FooterSection />
    </div>
  );
}
